name: OrySDK
targets:
  OrySDK:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [OrySDK]
    info:
      path: ./Info.plist
      version: latest
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
