//
// ActiveProjectInConsole.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The Active Project ID */
public struct ActiveProjectInConsole: Codable, JSONEncodable, Hashable {

    /** The Active Project ID  format: uuid */
    public var projectId: String?

    public init(projectId: String? = nil) {
        self.projectId = projectId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId = "project_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(projectId, forKey: .projectId)
    }
}

