//
// CheckPermissionResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The content of the allowed field is mirrored in the HTTP status code. */
public struct CheckPermissionResult: Codable, JSONEncodable, Hashable {

    /** whether the relation tuple is allowed */
    public var allowed: Bool

    public init(allowed: Bool) {
        self.allowed = allowed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case allowed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(allowed, forKey: .allowed)
    }
}

