//
// CreateJsonWebKeySet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Create JSON Web Key Set Request Body */
public struct CreateJsonWebKeySet: Codable, JSONEncodable, Hashable {

    /** JSON Web Key Algorithm  The algorithm to be used for creating the key. Supports `RS256`, `ES256`, `ES512`, `HS512`, and `HS256`. */
    public var alg: String
    /** JSON Web Key ID  The Key ID of the key to be created. */
    public var kid: String
    /** JSON Web Key Use  The \"use\" (public key use) parameter identifies the intended use of the public key. The \"use\" parameter is employed to indicate whether a public key is used for encrypting data or verifying the signature on data. Valid values are \"enc\" and \"sig\". */
    public var use: String

    public init(alg: String, kid: String, use: String) {
        self.alg = alg
        self.kid = kid
        self.use = use
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case alg
        case kid
        case use
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(alg, forKey: .alg)
        try container.encode(kid, forKey: .kid)
        try container.encode(use, forKey: .use)
    }
}

