//
// CreateProjectInvite.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Create Project Invite Request Body */
public struct CreateProjectInvite: Codable, JSONEncodable, Hashable {

    public var inviteeEmail: String?

    public init(inviteeEmail: String? = nil) {
        self.inviteeEmail = inviteeEmail
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case inviteeEmail = "invitee_email"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(inviteeEmail, forKey: .inviteeEmail)
    }
}

