//
// IdentityState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The state can either be &#x60;active&#x60; or &#x60;inactive&#x60;. */
public enum IdentityState: String, Codable, CaseIterable {
    case active = "active"
    case inactive = "inactive"
}
