//
// IdentityWithCredentialsOidcConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IdentityWithCredentialsOidcConfig: Codable, JSONEncodable, Hashable {

    public var config: IdentityWithCredentialsPasswordConfig?
    /** A list of OpenID Connect Providers */
    public var providers: [IdentityWithCredentialsOidcConfigProvider]?

    public init(config: IdentityWithCredentialsPasswordConfig? = nil, providers: [IdentityWithCredentialsOidcConfigProvider]? = nil) {
        self.config = config
        self.providers = providers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case config
        case providers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(config, forKey: .config)
        try container.encodeIfPresent(providers, forKey: .providers)
    }
}

