//
// Plan.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Plan: Codable, JSONEncodable, Hashable {

    /** Name is the name of the plan. */
    public var name: String
    /** Version is the version of the plan. The combination of `name@version` must be unique. */
    public var version: Int64

    public init(name: String, version: Int64) {
        self.name = name
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(version, forKey: .version)
    }
}

