//
// ProjectBranding.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The Project Branding */
public struct ProjectBranding: Codable, JSONEncodable, Hashable {

    /** The Customization Creation Date */
    public var createdAt: Date
    public var defaultTheme: ProjectBrandingTheme
    /** The customization ID. */
    public var id: String
    /** The Project's ID this customization is associated with */
    public var projectId: String
    /** The Project Branding Themes */
    public var themes: [ProjectBrandingTheme]
    /** Last Time Branding was Updated */
    public var updatedAt: Date

    public init(createdAt: Date, defaultTheme: ProjectBrandingTheme, id: String, projectId: String, themes: [ProjectBrandingTheme], updatedAt: Date) {
        self.createdAt = createdAt
        self.defaultTheme = defaultTheme
        self.id = id
        self.projectId = projectId
        self.themes = themes
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt = "created_at"
        case defaultTheme = "default_theme"
        case id
        case projectId = "project_id"
        case themes
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(defaultTheme, forKey: .defaultTheme)
        try container.encode(id, forKey: .id)
        try container.encode(projectId, forKey: .projectId)
        try container.encode(themes, forKey: .themes)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

