//
// ProjectServices.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProjectServices: Codable, JSONEncodable, Hashable {

    public var identity: ProjectServiceIdentity?
    public var oauth2: ProjectServiceOAuth2?
    public var permission: ProjectServicePermission?

    public init(identity: ProjectServiceIdentity? = nil, oauth2: ProjectServiceOAuth2? = nil, permission: ProjectServicePermission? = nil) {
        self.identity = identity
        self.oauth2 = oauth2
        self.permission = permission
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case identity
        case oauth2
        case permission
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(identity, forKey: .identity)
        try container.encodeIfPresent(oauth2, forKey: .oauth2)
        try container.encodeIfPresent(permission, forKey: .permission)
    }
}

