//
// RelationQuery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Relation Query */
public struct RelationQuery: Codable, JSONEncodable, Hashable {

    /** Namespace to query */
    public var namespace: String?
    /** Object to query */
    public var object: String?
    /** Relation to query */
    public var relation: String?
    /** SubjectID to query  Either SubjectSet or SubjectID can be provided. */
    public var subjectId: String?
    public var subjectSet: SubjectSet?

    public init(namespace: String? = nil, object: String? = nil, relation: String? = nil, subjectId: String? = nil, subjectSet: SubjectSet? = nil) {
        self.namespace = namespace
        self.object = object
        self.relation = relation
        self.subjectId = subjectId
        self.subjectSet = subjectSet
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case namespace
        case object
        case relation
        case subjectId = "subject_id"
        case subjectSet = "subject_set"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(namespace, forKey: .namespace)
        try container.encodeIfPresent(object, forKey: .object)
        try container.encodeIfPresent(relation, forKey: .relation)
        try container.encodeIfPresent(subjectId, forKey: .subjectId)
        try container.encodeIfPresent(subjectSet, forKey: .subjectSet)
    }
}

