//
// RelationshipPatch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Payload for patching a relationship */
public struct RelationshipPatch: Codable, JSONEncodable, Hashable {

    public enum Action: String, Codable, CaseIterable {
        case insert = "insert"
        case delete = "delete"
    }
    public var action: Action?
    public var relationTuple: Relationship?

    public init(action: Action? = nil, relationTuple: Relationship? = nil) {
        self.action = action
        self.relationTuple = relationTuple
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case action
        case relationTuple = "relation_tuple"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(action, forKey: .action)
        try container.encodeIfPresent(relationTuple, forKey: .relationTuple)
    }
}

