//
// SetProject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SetProject: Codable, JSONEncodable, Hashable {

    /** The name of the project. */
    public var name: String
    public var services: ProjectServices

    public init(name: String, services: ProjectServices) {
        self.name = name
        self.services = services
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case services
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(services, forKey: .services)
    }
}

