//
// SuccessfulNativeRegistration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The Response for Registration Flows via API */
public struct SuccessfulNativeRegistration: Codable, JSONEncodable, Hashable {

    public var identity: Identity
    public var session: Session?
    /** The Session Token  This field is only set when the session hook is configured as a post-registration hook.  A session token is equivalent to a session cookie, but it can be sent in the HTTP Authorization Header:  Authorization: bearer ${session-token}  The session token is only issued for API flows, not for Browser flows! */
    public var sessionToken: String?

    public init(identity: Identity, session: Session? = nil, sessionToken: String? = nil) {
        self.identity = identity
        self.session = session
        self.sessionToken = sessionToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case identity
        case session
        case sessionToken = "session_token"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(identity, forKey: .identity)
        try container.encodeIfPresent(session, forKey: .session)
        try container.encodeIfPresent(sessionToken, forKey: .sessionToken)
    }
}

