//
// TrustedOAuth2JwtGrantJsonWebKey.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** OAuth2 JWT Bearer Grant Type Issuer Trusted JSON Web Key */
public struct TrustedOAuth2JwtGrantJsonWebKey: Codable, JSONEncodable, Hashable {

    /** The \"key_id\" is key unique identifier (same as kid header in jws/jwt). */
    public var kid: String?
    /** The \"set\" is basically a name for a group(set) of keys. Will be the same as \"issuer\" in grant. */
    public var _set: String?

    public init(kid: String? = nil, _set: String? = nil) {
        self.kid = kid
        self._set = _set
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kid
        case _set = "set"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(kid, forKey: .kid)
        try container.encodeIfPresent(_set, forKey: ._set)
    }
}

