//
// TrustedOAuth2JwtGrantIssuer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** OAuth2 JWT Bearer Grant Type Issuer Trust Relationship */
public struct TrustedOAuth2JwtGrantIssuer: Codable, JSONEncodable, Hashable {

    /** The \"allow_any_subject\" indicates that the issuer is allowed to have any principal as the subject of the JWT. */
    public var allowAnySubject: Bool?
    /** The \"created_at\" indicates, when grant was created. */
    public var createdAt: Date?
    /** The \"expires_at\" indicates, when grant will expire, so we will reject assertion from \"issuer\" targeting \"subject\". */
    public var expiresAt: Date?
    public var id: String?
    /** The \"issuer\" identifies the principal that issued the JWT assertion (same as \"iss\" claim in JWT). */
    public var issuer: String?
    public var publicKey: TrustedOAuth2JwtGrantJsonWebKey?
    /** The \"scope\" contains list of scope values (as described in Section 3.3 of OAuth 2.0 [RFC6749]) */
    public var scope: [String]?
    /** The \"subject\" identifies the principal that is the subject of the JWT. */
    public var subject: String?

    public init(allowAnySubject: Bool? = nil, createdAt: Date? = nil, expiresAt: Date? = nil, id: String? = nil, issuer: String? = nil, publicKey: TrustedOAuth2JwtGrantJsonWebKey? = nil, scope: [String]? = nil, subject: String? = nil) {
        self.allowAnySubject = allowAnySubject
        self.createdAt = createdAt
        self.expiresAt = expiresAt
        self.id = id
        self.issuer = issuer
        self.publicKey = publicKey
        self.scope = scope
        self.subject = subject
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case allowAnySubject = "allow_any_subject"
        case createdAt = "created_at"
        case expiresAt = "expires_at"
        case id
        case issuer
        case publicKey = "public_key"
        case scope
        case subject
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(allowAnySubject, forKey: .allowAnySubject)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(issuer, forKey: .issuer)
        try container.encodeIfPresent(publicKey, forKey: .publicKey)
        try container.encodeIfPresent(scope, forKey: .scope)
        try container.encodeIfPresent(subject, forKey: .subject)
    }
}

