//
// UpdateSettingsFlowWithProfileMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Update Settings Flow with Profile Method */
public struct UpdateSettingsFlowWithProfileMethod: Codable, JSONEncodable, Hashable {

    /** The Anti-CSRF Token  This token is only required when performing browser flows. */
    public var csrfToken: String?
    /** Method  Should be set to profile when trying to update a profile. */
    public var method: String
    /** Traits  The identity's traits. */
    public var traits: AnyCodable

    public init(csrfToken: String? = nil, method: String, traits: AnyCodable) {
        self.csrfToken = csrfToken
        self.method = method
        self.traits = traits
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case csrfToken = "csrf_token"
        case method
        case traits
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(csrfToken, forKey: .csrfToken)
        try container.encode(method, forKey: .method)
        try container.encode(traits, forKey: .traits)
    }
}

